[2025-03-31 23:21:31,009: INFO: main: Welcome to our custom log]
[2025-04-01 22:56:56,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:56:56,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:56:56,938: INFO: common: created directory at: artifacts]
[2025-04-01 22:56:56,955: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:56:56,976: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 22:59:00,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:59:00,041: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:59:00,043: INFO: common: created directory at: artifacts]
[2025-04-01 22:59:00,044: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:59:00,048: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:02:14,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:02:14,810: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:02:14,812: INFO: common: created directory at: artifacts]
[2025-04-01 23:02:14,817: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:02:14,825: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:09:28,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:09:28,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:09:28,827: INFO: common: created directory at: artifacts]
[2025-04-01 23:09:28,830: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:09:28,834: INFO: 1626317731: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:26,140: INFO: 1626317731: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:27,956: INFO: 1626317731: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:18:48,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-02 08:18:48,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-02 08:18:48,793: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-02 08:18:48,795: INFO: common: created directory at: artifacts]
[2025-04-02 08:18:48,797: INFO: common: created directory at: data_ingestion]
[2025-04-02 08:18:48,798: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:00,610: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:02,620: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:37:02,621: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 19:53:46,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:53:46,321: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:01,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:01,326: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:18,547: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:18,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:55:23,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:55:23,303: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,330: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:00:03,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:00:03,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,349: INFO: common: created directory at: artifacts]
[2025-04-11 21:00:03,349: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:00:03,350: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:17:50,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:17:50,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:17:50,721: INFO: common: created directory at: artifacts]
[2025-04-11 21:17:50,721: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:17:50,721: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,727: ERROR: data_ingestion: Error downloading file: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1e3q72lfBRd5KX8KulVX39q34vW3y2M2b (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018CFFC5CFB0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
[2025-04-11 21:17:50,729: ERROR: data_ingestion: Error extracting file: Zip file not found: artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,729: ERROR: main: Zip file not found: artifacts/data_ingestion/data.zip]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.extract_zip_file()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 49, in extract_zip_file
    raise e
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 40, in extract_zip_file
    raise FileNotFoundError(f"Zip file not found: {self.config.local_data_file}")
FileNotFoundError: Zip file not found: artifacts/data_ingestion/data.zip
[2025-04-11 21:18:32,089: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:18:32,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:18:32,092: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:18:32,093: INFO: common: created directory at: artifacts]
[2025-04-11 21:18:32,093: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:18:32,093: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:47,390: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:48,184: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:20:48,184: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:20:52,516: INFO: main: *******************]
[2025-04-11 21:20:52,516: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:20:52,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:20:52,518: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:20:52,519: INFO: common: created directory at: artifacts]
[2025-04-11 21:20:52,520: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:20:52,520: ERROR: main: "'ConfigBox' object has no attribute 'include_top'"]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'include_top'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\config\configuration.py", line 50, in get_prepare_base_model_config
    params_include_top=self.params.INCLUDE_TOP,
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'include_top'"
[2025-04-11 21:24:36,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:24:36,497: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:24:36,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:24:36,515: INFO: common: created directory at: artifacts]
[2025-04-11 21:24:36,515: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:24:36,516: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:45,888: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:46,498: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:25:46,499: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:25:50,032: INFO: main: *******************]
[2025-04-11 21:25:50,033: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:25:50,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: created directory at: artifacts]
[2025-04-11 21:25:50,037: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:26:52,197: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,313: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,393: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:01:00,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:00,893: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:00,895: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:00,897: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:01,377: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:01:38,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:38,445: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:38,446: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:38,448: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:38,619: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:23,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:23,276: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:23,279: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:23,282: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:23,445: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:33,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:33,918: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:33,920: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:33,921: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:34,077: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:24:15,294: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:24:15,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:24:15,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:24:15,342: INFO: common: created directory at: artifacts]
[2025-04-11 22:24:15,343: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:24:15,345: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:25,913: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:26,558: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:26:26,559: INFO: main: *******************]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:26:26,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:26,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:26,562: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:26,563: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:26:26,879: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:26,984: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:27,083: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:26:27,084: INFO: main: *******************]
[2025-04-11 22:26:27,084: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:26:27,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:27,087: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:27,088: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:27,089: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:26:27,254: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:26:27,258: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\model_training.py", line 25, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-04-11 22:28:30,608: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:28:30,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:28:30,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:28:30,611: INFO: common: created directory at: artifacts]
[2025-04-11 22:28:30,611: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:28:30,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,420: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,964: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:29:43,964: INFO: main: *******************]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:29:43,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:29:44,224: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,400: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,495: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:29:44,496: INFO: main: *******************]
[2025-04-11 22:29:44,496: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:29:44,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:44,499: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:44,500: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:44,501: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:29:44,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:29:44,682: ERROR: main: Training.train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'callback_list'
[2025-04-11 22:34:04,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:34:04,032: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:34:04,036: INFO: common: created directory at: artifacts]
[2025-04-11 22:34:04,039: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:34:04,265: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:41,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:41,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:41,929: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:41,931: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:42,091: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:59,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:59,777: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:59,779: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:59,781: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:59,964: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:37:19,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:37:19,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:37:19,723: INFO: common: created directory at: artifacts]
[2025-04-11 22:37:19,724: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:37:19,893: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:01,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:01,404: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:01,406: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:01,409: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:01,558: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:11,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:11,676: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:11,678: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:11,679: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:11,856: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:39:57,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:39:57,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: created directory at: artifacts]
[2025-04-11 22:39:57,728: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:39:57,729: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:05,454: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:06,089: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:41:06,089: INFO: main: *******************]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:41:06,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:41:06,482: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,639: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:41:06,742: INFO: main: *******************]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:41:06,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,744: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,745: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,746: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:41:06,895: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:41:06,920: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-12 09:48:52,296: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-12 09:48:52,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:48:52,300: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:48:52,301: INFO: common: created directory at: artifacts]
[2025-04-12 09:48:52,302: INFO: common: created directory at: data_ingestion]
[2025-04-12 09:48:52,303: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-12 09:49:34,917: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-12 09:49:35,868: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-12 09:49:35,868: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-12 09:49:35,868: INFO: main: *******************]
[2025-04-12 09:49:35,869: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-12 09:49:35,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:49:35,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:49:35,874: INFO: common: created directory at: artifacts]
[2025-04-12 09:49:35,875: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-12 09:49:36,591: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-12 09:49:36,962: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-12 09:49:37,193: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-12 09:49:37,194: INFO: main: *******************]
[2025-04-12 09:49:37,194: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-12 09:49:37,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 09:49:37,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 09:49:37,204: INFO: common: created directory at: artifacts]
[2025-04-12 09:49:37,205: INFO: common: created directory at: artifacts\training]
[2025-04-12 09:49:37,489: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 09:49:37,539: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-12 10:01:11,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:01:11,200: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:01:11,202: INFO: common: created directory at: artifacts]
[2025-04-12 10:01:11,204: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:01:11,567: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:01:19,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:01:19,578: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:01:19,580: INFO: common: created directory at: artifacts]
[2025-04-12 10:01:19,583: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:01:19,829: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:02:45,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:02:45,743: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:02:45,745: INFO: common: created directory at: artifacts]
[2025-04-12 10:02:45,748: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:02:45,949: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:08:39,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:08:39,782: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:08:39,784: INFO: common: created directory at: artifacts]
[2025-04-12 10:08:39,786: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:08:40,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:09:01,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:09:01,683: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:09:01,685: INFO: common: created directory at: artifacts]
[2025-04-12 10:09:01,687: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:09:01,862: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:11:24,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:11:24,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:11:24,110: INFO: common: created directory at: artifacts]
[2025-04-12 10:11:24,112: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:11:24,270: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:13:59,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:13:59,886: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:13:59,890: INFO: common: created directory at: artifacts]
[2025-04-12 10:13:59,891: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:14:00,066: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:15:29,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:15:29,996: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:15:29,999: INFO: common: created directory at: artifacts]
[2025-04-12 10:15:30,002: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:15:30,192: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:16:13,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:16:13,666: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:16:13,667: INFO: common: created directory at: artifacts]
[2025-04-12 10:16:13,670: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:16:13,838: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:20:20,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:20:20,160: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:20:20,160: INFO: common: created directory at: artifacts]
[2025-04-12 10:20:20,161: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:20:20,308: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:22:30,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:22:30,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:22:30,284: INFO: common: created directory at: artifacts]
[2025-04-12 10:22:30,285: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:06,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:23:06,980: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:23:06,982: INFO: common: created directory at: artifacts]
[2025-04-12 10:23:06,983: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:36,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-12 10:23:36,057: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-12 10:23:36,058: INFO: common: created directory at: artifacts]
[2025-04-12 10:23:36,060: INFO: common: created directory at: artifacts\training]
[2025-04-12 10:23:36,264: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-12 10:30:55,241: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:15:11,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:15:11,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:15:11,744: INFO: common: created directory at: artifacts]
[2025-04-13 03:15:11,746: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 03:15:12,137: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:15:12,287: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:24:13,323: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-13 03:24:13,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:24:13,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:24:13,351: INFO: common: created directory at: artifacts]
[2025-04-13 03:24:13,351: INFO: common: created directory at: data_ingestion]
[2025-04-13 03:24:13,352: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-13 03:37:28,685: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-13 03:37:29,449: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-13 03:37:29,449: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-13 03:37:29,449: INFO: main: *******************]
[2025-04-13 03:37:29,449: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-13 03:37:29,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 03:37:29,474: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 03:37:29,474: INFO: common: created directory at: artifacts]
[2025-04-13 03:37:29,475: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 03:37:29,891: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:37:30,030: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 03:37:30,123: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-13 23:29:32,139: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:29:32,143: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:29:32,147: INFO: common: created directory at: artifacts]
[2025-04-13 23:29:32,151: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:33:53,785: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-13 23:33:53,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:33:53,788: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:33:53,788: INFO: common: created directory at: artifacts]
[2025-04-13 23:33:53,789: INFO: common: created directory at: data_ingestion]
[2025-04-13 23:33:53,789: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-13 23:35:42,263: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-13 23:35:42,879: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-13 23:35:42,880: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-13 23:35:42,880: INFO: main: *******************]
[2025-04-13 23:35:42,880: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-13 23:35:42,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:35:42,883: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:35:42,883: INFO: common: created directory at: artifacts]
[2025-04-13 23:35:42,884: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-13 23:35:43,427: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 23:35:43,587: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-13 23:35:43,679: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-13 23:37:17,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:37:17,333: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:37:17,335: INFO: common: created directory at: artifacts]
[2025-04-13 23:37:17,337: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:37:17,566: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:39:27,979: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:39:27,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:39:27,986: INFO: common: created directory at: artifacts]
[2025-04-13 23:39:27,989: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:39:28,230: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:39:30,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:39:30,127: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:39:30,128: INFO: common: created directory at: artifacts]
[2025-04-13 23:39:30,129: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:39:30,272: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:41:44,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:41:44,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:41:44,508: INFO: common: created directory at: artifacts]
[2025-04-13 23:41:44,510: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:41:44,663: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:42:52,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:42:52,031: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:42:52,032: INFO: common: created directory at: artifacts]
[2025-04-13 23:42:52,033: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:42:52,173: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:43:24,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-13 23:43:24,878: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-13 23:43:24,880: INFO: common: created directory at: artifacts]
[2025-04-13 23:43:24,883: INFO: common: created directory at: artifacts\training]
[2025-04-13 23:43:25,034: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-13 23:49:46,698: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:30:40,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:30:40,329: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:30:40,329: INFO: common: created directory at: artifacts]
[2025-04-14 09:32:26,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:32:26,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:32:26,688: INFO: common: created directory at: artifacts]
[2025-04-14 09:32:26,690: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:32:27,346: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 09:33:26,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:33:26,116: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:33:26,118: INFO: common: created directory at: artifacts]
[2025-04-14 09:33:26,119: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:33:59,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:33:59,198: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:33:59,200: INFO: common: created directory at: artifacts]
[2025-04-14 09:33:59,202: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:34:56,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:34:56,614: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:34:56,617: INFO: common: created directory at: artifacts]
[2025-04-14 09:34:56,621: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:38:14,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:38:14,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:38:14,320: INFO: common: created directory at: artifacts]
[2025-04-14 09:40:45,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:40:45,822: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:40:45,825: INFO: common: created directory at: artifacts]
[2025-04-14 09:40:45,829: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:40:45,934: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:42:20,048: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:42:20,056: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:42:20,061: INFO: common: created directory at: artifacts]
[2025-04-14 09:42:20,062: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:42:20,251: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:44:50,468: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:44:50,474: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:44:50,476: INFO: common: created directory at: artifacts]
[2025-04-14 09:44:50,480: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:44:50,706: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:45:19,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:45:19,945: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:45:19,947: INFO: common: created directory at: artifacts]
[2025-04-14 09:45:19,949: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:45:20,115: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 09:46:39,426: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-14 09:46:39,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:46:39,428: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:46:39,429: INFO: common: created directory at: artifacts]
[2025-04-14 09:46:39,430: INFO: common: created directory at: data_ingestion]
[2025-04-14 09:46:39,430: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-14 09:48:14,575: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-14 09:48:15,179: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-14 09:48:15,180: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-14 09:48:15,180: INFO: main: *******************]
[2025-04-14 09:48:15,180: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-14 09:48:15,182: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:48:15,184: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:48:15,184: INFO: common: created directory at: artifacts]
[2025-04-14 09:48:15,185: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-14 09:48:15,558: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:48:15,708: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 09:48:15,809: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-14 09:48:15,810: INFO: main: *******************]
[2025-04-14 09:48:15,810: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-14 09:48:15,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 09:48:15,820: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 09:48:15,820: INFO: common: created directory at: artifacts]
[2025-04-14 09:48:15,821: INFO: common: created directory at: artifacts\training]
[2025-04-14 09:48:15,978: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 09:48:16,015: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-14 23:24:10,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:24:10,469: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:24:10,471: INFO: common: created directory at: artifacts]
[2025-04-14 23:24:10,474: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:24:11,039: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-14 23:25:04,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:25:04,987: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:25:04,990: INFO: common: created directory at: artifacts]
[2025-04-14 23:25:04,991: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:25:05,355: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-14 23:25:22,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:25:22,050: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:25:22,053: INFO: common: created directory at: artifacts]
[2025-04-14 23:25:22,057: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:25:22,330: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 23:28:01,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:28:01,426: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:28:01,437: INFO: common: created directory at: artifacts]
[2025-04-14 23:28:01,449: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:28:02,062: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-14 23:28:24,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-14 23:28:24,076: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-14 23:28:24,078: INFO: common: created directory at: artifacts]
[2025-04-14 23:28:24,080: INFO: common: created directory at: artifacts\training]
[2025-04-14 23:28:24,294: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:35:31,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:35:31,572: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:35:31,574: INFO: common: created directory at: artifacts]
[2025-04-18 18:35:31,576: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:35:32,021: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:36:20,062: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:36:20,070: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:36:20,074: INFO: common: created directory at: artifacts]
[2025-04-18 18:36:20,077: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:36:20,344: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:37:19,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:37:19,133: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:37:19,135: INFO: common: created directory at: artifacts]
[2025-04-18 18:37:19,138: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:37:19,303: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:38:42,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:38:42,297: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:38:42,298: INFO: common: created directory at: artifacts]
[2025-04-18 18:38:42,300: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:38:42,433: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:40:42,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:40:42,761: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:40:42,770: INFO: common: created directory at: artifacts]
[2025-04-18 18:40:42,783: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:40:42,989: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:41:41,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:41:41,367: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:41:41,369: INFO: common: created directory at: artifacts]
[2025-04-18 18:41:41,371: INFO: common: created directory at: artifacts\training]
[2025-04-18 18:41:41,518: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-04-18 18:49:31,488: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 18:49:31,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:49:31,490: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:49:31,491: INFO: common: created directory at: artifacts]
[2025-04-18 18:49:31,492: INFO: common: created directory at: data_ingestion]
[2025-04-18 18:49:31,493: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 18:50:34,017: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 18:50:34,694: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 18:50:34,694: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 18:50:34,695: INFO: main: *******************]
[2025-04-18 18:50:34,695: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 18:50:34,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 18:50:34,697: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 18:50:34,697: INFO: common: created directory at: artifacts]
[2025-04-18 18:50:34,698: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 18:50:35,172: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 18:50:35,306: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 18:50:35,428: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 19:00:42,592: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:00:42,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:00:42,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:00:42,595: INFO: common: created directory at: artifacts]
[2025-04-18 19:00:42,596: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:00:42,596: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:01:50,185: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:01:50,800: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:01:50,800: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:01:50,800: INFO: main: *******************]
[2025-04-18 19:01:50,801: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:01:50,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:01:50,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:01:50,804: INFO: common: created directory at: artifacts]
[2025-04-18 19:01:50,805: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:01:51,176: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:01:51,304: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:01:51,409: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 19:04:40,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:04:40,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:04:40,763: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:04:40,764: INFO: common: created directory at: artifacts]
[2025-04-18 19:04:40,765: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:04:40,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:06:45,327: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:06:45,953: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:06:45,953: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:06:45,954: INFO: main: *******************]
[2025-04-18 19:06:45,954: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:06:45,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:06:45,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:06:45,956: INFO: common: created directory at: artifacts]
[2025-04-18 19:06:45,957: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:06:45,958: ERROR: main: "'ConfigBox' object has no attribute 'updated_base_model_path'"]
Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'updated_base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'updated_base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 25, in <module>
    prepare_base_model.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\config\configuration.py", line 45, in get_prepare_base_model_config
    updated_base_model_path=Path(config.updated_base_model_path),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\AppData\Local\Programs\Python\Python312\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'updated_base_model_path'"
[2025-04-18 19:13:48,837: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 19:13:48,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:13:48,865: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:13:48,866: INFO: common: created directory at: artifacts]
[2025-04-18 19:13:48,867: INFO: common: created directory at: data_ingestion]
[2025-04-18 19:13:48,867: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 19:15:14,051: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 19:15:14,693: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 19:15:14,693: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 19:15:14,693: INFO: main: *******************]
[2025-04-18 19:15:14,693: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 19:15:14,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 19:15:14,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 19:15:14,696: INFO: common: created directory at: artifacts]
[2025-04-18 19:15:14,697: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 19:15:14,958: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:15:15,069: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 19:15:15,176: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 20:43:49,912: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 20:43:49,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:43:49,916: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:43:49,916: INFO: common: created directory at: artifacts]
[2025-04-18 20:43:49,917: INFO: common: created directory at: data_ingestion]
[2025-04-18 20:43:49,917: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 20:45:39,784: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 20:45:40,453: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 20:45:40,453: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 20:45:40,453: INFO: main: *******************]
[2025-04-18 20:45:40,453: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 20:45:40,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:45:40,456: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:45:40,456: INFO: common: created directory at: artifacts]
[2025-04-18 20:45:40,456: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 20:45:40,725: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 20:45:40,834: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 20:45:40,933: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 20:55:35,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:55:35,590: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:55:35,592: INFO: common: created directory at: artifacts]
[2025-04-18 20:55:35,595: INFO: common: created directory at: artifacts\training]
[2025-04-18 20:55:35,942: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 20:55:54,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 20:55:54,335: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 20:55:54,337: INFO: common: created directory at: artifacts]
[2025-04-18 20:55:54,339: INFO: common: created directory at: artifacts\training]
[2025-04-18 20:55:54,487: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:18:00,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:18:00,897: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:18:00,900: INFO: common: created directory at: artifacts]
[2025-04-18 21:18:00,903: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:18:01,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:18:29,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:18:29,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:18:29,788: INFO: common: created directory at: artifacts]
[2025-04-18 21:18:29,791: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:18:30,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:21:00,299: WARNING: module_wrapper: From C:\Users\Prarthana\AppData\Local\Temp\ipykernel_23908\2490681004.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-04-18 21:21:03,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:21:03,722: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:21:03,725: INFO: common: created directory at: artifacts]
[2025-04-18 21:21:03,727: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:21:03,946: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:23:11,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:23:11,647: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:23:11,656: INFO: common: created directory at: artifacts]
[2025-04-18 21:23:11,664: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:23:11,879: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 21:25:46,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 21:25:46,065: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 21:25:46,066: INFO: common: created directory at: artifacts]
[2025-04-18 21:25:46,068: INFO: common: created directory at: artifacts\training]
[2025-04-18 21:33:46,146: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:24:27,068: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 23:24:27,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:24:27,074: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:24:27,075: INFO: common: created directory at: artifacts]
[2025-04-18 23:24:27,075: INFO: common: created directory at: data_ingestion]
[2025-04-18 23:24:27,076: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 23:25:28,416: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 23:25:29,099: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 23:25:29,099: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 23:25:29,099: INFO: main: *******************]
[2025-04-18 23:25:29,099: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 23:25:29,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:25:29,102: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:25:29,102: INFO: common: created directory at: artifacts]
[2025-04-18 23:25:29,103: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 23:25:29,452: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:25:29,580: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:25:29,678: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 23:25:29,678: INFO: main: *******************]
[2025-04-18 23:25:29,678: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-18 23:25:29,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:25:29,681: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:25:29,681: INFO: common: created directory at: artifacts]
[2025-04-18 23:25:29,684: INFO: common: created directory at: artifacts\training]
[2025-04-18 23:31:33,550: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:31:33,714: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-18 23:31:33,715: INFO: main: *******************]
[2025-04-18 23:31:33,716: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-18 23:31:33,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:31:33,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:31:33,723: INFO: common: created directory at: artifacts]
[2025-04-18 23:31:34,004: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 23:32:10,735: INFO: common: json file saved at: scores.json]
[2025-04-18 23:32:10,738: INFO: common: json file saved at: scores.json]
[2025-04-18 23:32:10,739: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-18 23:48:23,558: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-18 23:48:23,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:48:23,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:48:23,562: INFO: common: created directory at: artifacts]
[2025-04-18 23:48:23,563: INFO: common: created directory at: data_ingestion]
[2025-04-18 23:48:23,566: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-18 23:49:15,124: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-18 23:49:16,279: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-18 23:49:16,279: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-18 23:49:16,280: INFO: main: *******************]
[2025-04-18 23:49:16,280: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-18 23:49:16,281: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:49:16,284: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:49:16,284: INFO: common: created directory at: artifacts]
[2025-04-18 23:49:16,286: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-18 23:49:16,777: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:49:16,989: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:49:17,167: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-18 23:49:17,167: INFO: main: *******************]
[2025-04-18 23:49:17,167: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-18 23:49:17,170: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:49:17,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:49:17,173: INFO: common: created directory at: artifacts]
[2025-04-18 23:49:17,174: INFO: common: created directory at: artifacts\training]
[2025-04-18 23:56:03,512: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-18 23:56:03,673: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-18 23:56:03,673: INFO: main: *******************]
[2025-04-18 23:56:03,674: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-18 23:56:03,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-18 23:56:03,679: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-18 23:56:03,681: INFO: common: created directory at: artifacts]
[2025-04-18 23:56:03,918: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-18 23:56:35,015: INFO: common: json file saved at: scores.json]
[2025-04-18 23:56:35,019: INFO: common: json file saved at: scores.json]
[2025-04-18 23:56:35,020: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 00:11:01,025: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 00:11:01,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:11:01,028: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:11:01,029: INFO: common: created directory at: artifacts]
[2025-04-19 00:11:01,030: INFO: common: created directory at: data_ingestion]
[2025-04-19 00:11:01,031: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 00:11:42,973: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 00:11:43,591: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 00:11:43,591: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 00:11:43,592: INFO: main: *******************]
[2025-04-19 00:11:43,592: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 00:11:43,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:11:43,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:11:43,595: INFO: common: created directory at: artifacts]
[2025-04-19 00:11:43,595: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 00:11:43,882: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:11:44,049: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:11:44,151: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 00:11:44,151: INFO: main: *******************]
[2025-04-19 00:11:44,152: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 00:11:44,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:11:44,155: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:11:44,155: INFO: common: created directory at: artifacts]
[2025-04-19 00:11:44,156: INFO: common: created directory at: artifacts\training]
[2025-04-19 00:17:55,284: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:17:55,518: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 00:17:55,519: INFO: main: *******************]
[2025-04-19 00:17:55,519: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 00:17:55,522: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:17:55,525: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:17:55,526: INFO: common: created directory at: artifacts]
[2025-04-19 00:17:55,790: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 00:18:33,454: INFO: common: json file saved at: scores.json]
[2025-04-19 00:18:33,458: INFO: common: json file saved at: scores.json]
[2025-04-19 00:18:33,459: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 00:20:07,739: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 00:20:07,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:20:07,742: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:20:07,744: INFO: common: created directory at: artifacts]
[2025-04-19 00:20:07,744: INFO: common: created directory at: data_ingestion]
[2025-04-19 00:20:07,745: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 00:21:03,834: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 00:21:04,647: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 00:21:04,648: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 00:21:04,648: INFO: main: *******************]
[2025-04-19 00:21:04,648: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 00:21:04,650: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:21:04,651: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:21:04,652: INFO: common: created directory at: artifacts]
[2025-04-19 00:21:04,653: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 00:21:05,102: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:21:05,286: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:21:05,423: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 00:21:05,423: INFO: main: *******************]
[2025-04-19 00:21:05,424: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 00:21:05,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:21:05,427: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:21:05,428: INFO: common: created directory at: artifacts]
[2025-04-19 00:21:05,429: INFO: common: created directory at: artifacts\training]
[2025-04-19 00:27:37,332: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 00:27:37,511: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 00:27:37,511: INFO: main: *******************]
[2025-04-19 00:27:37,511: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 00:27:37,514: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 00:27:37,517: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 00:27:37,518: INFO: common: created directory at: artifacts]
[2025-04-19 00:27:37,781: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 00:28:15,296: INFO: common: json file saved at: scores.json]
[2025-04-19 00:28:15,299: INFO: common: json file saved at: scores.json]
[2025-04-19 00:29:11,784: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')': /PrarthanaGanegama/kidney_disease_classification.mlflow/api/2.0/mlflow-artifacts/artifacts/50eb299c24414be7aa2509b798ac6642/00266c6e8afe40b2b1c35228b6451c29/artifacts/model/data/model.keras]
[2025-04-19 00:30:40,074: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 01:05:43,692: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 01:05:43,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:05:43,697: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:05:43,698: INFO: common: created directory at: artifacts]
[2025-04-19 01:05:43,698: INFO: common: created directory at: data_ingestion]
[2025-04-19 01:05:43,699: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 01:06:12,970: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 01:06:13,951: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 01:06:13,952: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 01:07:39,599: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 01:07:39,605: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:07:39,607: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:07:39,608: INFO: common: created directory at: artifacts]
[2025-04-19 01:07:39,608: INFO: common: created directory at: data_ingestion]
[2025-04-19 01:07:39,609: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 01:08:17,536: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 01:08:18,463: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 01:08:18,464: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 01:08:46,109: INFO: stage_02_prepare_base_model: *******************]
[2025-04-19 01:08:46,109: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 01:08:46,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:08:46,113: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:08:46,113: INFO: common: created directory at: artifacts]
[2025-04-19 01:08:46,114: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 01:08:46,570: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:08:46,733: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:08:46,864: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 01:08:55,397: INFO: stage_03_model_training: *******************]
[2025-04-19 01:08:55,397: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-04-19 01:08:55,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:08:55,401: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:08:55,401: INFO: common: created directory at: artifacts]
[2025-04-19 01:08:55,402: INFO: common: created directory at: artifacts\training]
[2025-04-19 01:14:37,297: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:14:37,469: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 01:14:50,740: INFO: stage_04_model_evaluation: *******************]
[2025-04-19 01:14:50,741: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 01:14:50,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:14:50,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:14:50,747: INFO: common: created directory at: artifacts]
[2025-04-19 01:14:51,061: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 01:15:24,370: INFO: common: json file saved at: scores.json]
[2025-04-19 01:15:24,374: INFO: common: json file saved at: scores.json]
[2025-04-19 01:17:52,024: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 01:26:57,277: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 01:26:57,278: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 01:27:13,618: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:27:13] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:27:13,773: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:27:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-04-19 01:27:21,494: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:27:21] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:27:33,080: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:27:33] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:27:57,932: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:27:57] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:32:09,239: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:32:09] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:32:11,092: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:32:11] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:38:07,968: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 01:38:07,968: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 01:38:18,600: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:38:18] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:43:08,870: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 01:43:08,870: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 01:43:18,785: INFO: _internal: 192.168.166.217 - - [19/Apr/2025 01:43:18] "GET / HTTP/1.1" 200 -]
[2025-04-19 01:43:20,210: INFO: _internal: 192.168.166.217 - - [19/Apr/2025 01:43:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-04-19 01:44:42,375: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:44:42] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 01:44:42,664: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 01:44:42,712: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:44:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 01:44:44,954: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 01:44:44,965: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:44:44] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 01:45:09,046: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 01:45:09,070: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:45:09,085: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:45:09,090: INFO: common: created directory at: artifacts]
[2025-04-19 01:45:09,094: INFO: common: created directory at: data_ingestion]
[2025-04-19 01:45:09,098: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 01:45:54,313: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 01:45:55,122: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 01:45:55,123: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 01:45:55,123: INFO: main: *******************]
[2025-04-19 01:45:55,123: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 01:45:55,124: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:45:55,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:45:55,127: INFO: common: created directory at: artifacts]
[2025-04-19 01:45:55,128: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 01:45:55,773: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:45:56,025: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:45:56,171: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 01:45:56,172: INFO: main: *******************]
[2025-04-19 01:45:56,172: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 01:45:56,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:45:56,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:45:56,177: INFO: common: created directory at: artifacts]
[2025-04-19 01:45:56,178: INFO: common: created directory at: artifacts\training]
[2025-04-19 01:51:18,348: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:51:18] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 01:51:18,627: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 01:51:18,649: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:51:18] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 01:51:23,581: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:51:23] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 01:51:23,914: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 01:51:23,930: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:51:23] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 01:51:29,281: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:51:29] "OPTIONS /train?_=1745007663651 HTTP/1.1" 200 -]
[2025-04-19 01:52:41,912: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 01:52:41,919: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:52:41,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:52:41,968: INFO: common: created directory at: artifacts]
[2025-04-19 01:52:42,008: INFO: common: created directory at: data_ingestion]
[2025-04-19 01:52:42,040: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 01:53:21,951: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 01:53:24,171: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:53:24,352: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 01:53:24,352: INFO: main: *******************]
[2025-04-19 01:53:24,352: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 01:53:24,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:53:24,359: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:53:24,361: INFO: common: created directory at: artifacts]
[2025-04-19 01:53:24,785: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 01:53:25,431: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 01:53:25,433: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 01:53:25,434: INFO: main: *******************]
[2025-04-19 01:53:25,435: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 01:53:25,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:53:25,446: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:53:25,449: INFO: common: created directory at: artifacts]
[2025-04-19 01:53:25,451: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 01:53:26,641: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:53:27,950: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 01:53:28,628: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 01:53:28,639: INFO: main: *******************]
[2025-04-19 01:53:28,660: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 01:53:28,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 01:53:28,677: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 01:53:28,681: INFO: common: created directory at: artifacts]
[2025-04-19 01:53:28,684: INFO: common: created directory at: artifacts\training]
[2025-04-19 01:54:44,496: INFO: common: json file saved at: scores.json]
[2025-04-19 01:54:44,547: INFO: common: json file saved at: scores.json]
[2025-04-19 01:59:14,677: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 01:59:20,989: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:59:20] "GET /train?_=1745007200179 HTTP/1.1" 200 -]
[2025-04-19 01:59:31,237: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:59:31] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 01:59:31,504: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 01:59:31,523: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 01:59:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 02:01:57,226: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 02:01:57,420: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 02:01:57,421: INFO: main: *******************]
[2025-04-19 02:01:57,422: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 02:01:57,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 02:01:57,430: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 02:01:57,431: INFO: common: created directory at: artifacts]
[2025-04-19 02:01:58,179: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 02:02:54,003: INFO: common: json file saved at: scores.json]
[2025-04-19 02:02:54,007: INFO: common: json file saved at: scores.json]
[2025-04-19 02:02:54,008: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 02:02:56,054: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:02:56] "GET /train?_=1745007663651 HTTP/1.1" 200 -]
[2025-04-19 02:07:02,524: INFO: _internal: 192.168.166.217 - - [19/Apr/2025 02:07:02] "GET / HTTP/1.1" 200 -]
[2025-04-19 02:07:14,615: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:07:14] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 02:07:14,866: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    #model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 02:07:14,928: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:07:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 02:08:03,578: INFO: _internal: 192.168.166.217 - - [19/Apr/2025 02:08:03] "GET / HTTP/1.1" 200 -]
[2025-04-19 02:08:18,165: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:08:18] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 02:08:18,450: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    #model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-04-19 02:08:18,523: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:08:18] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-19 02:09:53,782: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 02:09:53,782: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 02:09:58,022: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:09:58] "GET / HTTP/1.1" 200 -]
[2025-04-19 02:10:11,704: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:10:11] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 02:10:13,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 02:10:15,042: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:10:15] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 02:11:28,358: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 02:11:28,359: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 02:11:32,216: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:11:32] "GET / HTTP/1.1" 200 -]
[2025-04-19 02:11:42,066: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:11:42] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 02:11:43,472: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 02:11:44,875: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:11:44] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 02:15:02,720: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 02:15:02,720: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 02:15:09,151: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:15:09] "GET / HTTP/1.1" 200 -]
[2025-04-19 02:15:19,839: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:15:19] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 02:15:20,302: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 02:15:20,644: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:15:20] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 02:15:47,225: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 02:15:47,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 02:15:47,227: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 02:15:47,228: INFO: common: created directory at: artifacts]
[2025-04-19 02:15:47,229: INFO: common: created directory at: data_ingestion]
[2025-04-19 02:15:47,229: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 02:16:25,829: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 02:16:26,407: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 02:16:26,407: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 02:16:26,407: INFO: main: *******************]
[2025-04-19 02:16:26,408: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 02:16:26,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 02:16:26,410: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 02:16:26,410: INFO: common: created directory at: artifacts]
[2025-04-19 02:16:26,411: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 02:16:26,764: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 02:16:26,929: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 02:16:26,998: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 02:16:26,999: INFO: main: *******************]
[2025-04-19 02:16:26,999: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 02:16:27,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 02:16:27,003: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 02:16:27,005: INFO: common: created directory at: artifacts]
[2025-04-19 02:16:27,005: INFO: common: created directory at: artifacts\training]
[2025-04-19 02:22:47,289: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 02:22:47,551: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 02:22:47,552: INFO: main: *******************]
[2025-04-19 02:22:47,553: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 02:22:47,556: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 02:22:47,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 02:22:47,562: INFO: common: created directory at: artifacts]
[2025-04-19 02:22:47,938: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 02:23:24,727: INFO: common: json file saved at: scores.json]
[2025-04-19 02:23:24,732: INFO: common: json file saved at: scores.json]
[2025-04-19 02:23:24,733: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 02:23:25,838: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 02:23:25] "GET /train?_=1745009109280 HTTP/1.1" 200 -]
[2025-04-19 07:52:33,849: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 07:52:33] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 07:52:34,921: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 07:52:36,328: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 07:52:36] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 07:52:45,162: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 07:52:45] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 07:52:45,878: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 07:52:47,140: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 07:52:47] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:07:34,597: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 08:07:34,598: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 08:07:38,286: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:07:38] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:07:57,116: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 08:07:57,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:07:57,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:07:57,121: INFO: common: created directory at: artifacts]
[2025-04-19 08:07:57,121: INFO: common: created directory at: data_ingestion]
[2025-04-19 08:07:57,121: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 08:08:46,883: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 08:08:47,665: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 08:08:47,666: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 08:08:47,666: INFO: main: *******************]
[2025-04-19 08:08:47,666: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 08:08:47,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:08:47,669: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:08:47,670: INFO: common: created directory at: artifacts]
[2025-04-19 08:08:47,670: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 08:08:48,308: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:08:48,690: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:08:48,965: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 08:08:48,965: INFO: main: *******************]
[2025-04-19 08:08:48,966: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 08:08:48,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:08:48,971: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:08:48,972: INFO: common: created directory at: artifacts]
[2025-04-19 08:08:48,972: INFO: common: created directory at: artifacts\training]
[2025-04-19 08:14:26,839: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:14:26,979: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 08:14:26,979: INFO: main: *******************]
[2025-04-19 08:14:26,979: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 08:14:26,981: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:14:26,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:14:26,984: INFO: common: created directory at: artifacts]
[2025-04-19 08:14:27,219: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:15:01,519: INFO: common: json file saved at: scores.json]
[2025-04-19 08:15:01,521: INFO: common: json file saved at: scores.json]
[2025-04-19 08:15:01,522: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 08:15:02,700: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:15:02] "GET /train?_=1745030258527 HTTP/1.1" 200 -]
[2025-04-19 08:16:31,933: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:16:31] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:16:32,629: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:16:33,292: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:16:33] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:16:45,898: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:16:45] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:16:46,412: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:16:46,926: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:16:46] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:16:58,029: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:16:58] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:16:59,030: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:17:00,588: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:17:00] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:21:14,646: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 08:21:14,647: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 08:21:26,163: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:21:26] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:21:35,899: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:21:35] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:21:37,583: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:21:37,763: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:21:39,717: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:21:39,718: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:21:39,721: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:21:39] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:22:52,975: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:22:52] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:22:53,944: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:22:54,047: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:22:55,547: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:22:55,548: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:22:55,550: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:22:55] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:23:00,538: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:23:00] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:23:01,453: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:23:01,510: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:23:02,990: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:23:02,992: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:23:02,994: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:23:02] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:26:35,968: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:26:35] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:26:36,806: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:26:36,864: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:26:38,424: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:26:38,425: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:26:38,427: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:26:38] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:26:46,115: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:26:46] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:26:47,423: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:26:47,535: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:26:49,229: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001C4A3D03880> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-19 08:26:49,306: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:26:49,307: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:26:49,308: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:26:49] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:27:00,820: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 08:27:00,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:27:00,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:27:00,825: INFO: common: created directory at: artifacts]
[2025-04-19 08:27:00,826: INFO: common: created directory at: data_ingestion]
[2025-04-19 08:27:00,826: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 08:28:36,967: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 08:28:37,848: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 08:28:37,848: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 08:28:37,849: INFO: main: *******************]
[2025-04-19 08:28:37,850: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 08:28:37,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:28:37,856: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:28:37,857: INFO: common: created directory at: artifacts]
[2025-04-19 08:28:37,857: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 08:28:38,242: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:28:38,525: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:28:38,655: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 08:28:38,655: INFO: main: *******************]
[2025-04-19 08:28:38,655: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 08:28:38,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:28:38,659: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:28:38,660: INFO: common: created directory at: artifacts]
[2025-04-19 08:28:38,661: INFO: common: created directory at: artifacts\training]
[2025-04-19 08:34:12,985: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:34:13,143: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 08:34:13,144: INFO: main: *******************]
[2025-04-19 08:34:13,144: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 08:34:13,146: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:34:13,147: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:34:13,148: INFO: common: created directory at: artifacts]
[2025-04-19 08:34:13,440: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:34:51,422: INFO: common: json file saved at: scores.json]
[2025-04-19 08:34:51,423: INFO: common: json file saved at: scores.json]
[2025-04-19 08:34:51,424: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 08:34:53,175: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:34:53] "GET /train?_=1745031086376 HTTP/1.1" 200 -]
[2025-04-19 08:35:20,170: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:35:20] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:35:21,415: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:35:21,530: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:35:23,515: WARNING: polymorphic_function: 6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001C4A3E0E2A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-19 08:35:24,597: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:35:24,603: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:35:24,608: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:35:24] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:39:07,044: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:39:07] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:39:08,155: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:39:08,255: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:39:10,181: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:39:10,181: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:39:10,183: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:39:10] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:39:23,324: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-19 08:39:23,326: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:39:23,328: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:39:23,330: INFO: common: created directory at: artifacts]
[2025-04-19 08:39:23,330: INFO: common: created directory at: data_ingestion]
[2025-04-19 08:39:23,331: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-19 08:40:45,054: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-19 08:40:45,893: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-19 08:40:45,894: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-19 08:40:45,894: INFO: main: *******************]
[2025-04-19 08:40:45,894: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-19 08:40:45,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:40:45,897: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:40:45,899: INFO: common: created directory at: artifacts]
[2025-04-19 08:40:45,899: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-19 08:40:46,371: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:40:46,562: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:40:46,686: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-19 08:40:46,687: INFO: main: *******************]
[2025-04-19 08:40:46,687: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-19 08:40:46,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:40:46,691: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:40:46,691: INFO: common: created directory at: artifacts]
[2025-04-19 08:40:46,692: INFO: common: created directory at: artifacts\training]
[2025-04-19 08:46:24,997: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-19 08:46:25,144: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-19 08:46:25,145: INFO: main: *******************]
[2025-04-19 08:46:25,145: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-19 08:46:25,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-19 08:46:25,149: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-19 08:46:25,150: INFO: common: created directory at: artifacts]
[2025-04-19 08:46:25,418: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:47:01,499: INFO: common: json file saved at: scores.json]
[2025-04-19 08:47:01,502: INFO: common: json file saved at: scores.json]
[2025-04-19 08:47:01,502: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-19 08:47:02,935: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:47:02] "GET /train?_=1745031086377 HTTP/1.1" 200 -]
[2025-04-19 08:47:49,403: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:47:49] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:47:50,459: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:47:50,517: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:47:52,198: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:47:52,199: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:47:52,201: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:47:52] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:52:23,824: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:52:23] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:52:24,857: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:52:24,961: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:52:27,989: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:52:27,993: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:52:27,997: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:52:27] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:53:39,413: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:53:39] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:53:43,111: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:53:43] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:53:52,003: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:53:52] "OPTIONS /predict HTTP/1.1" 200 -]
[2025-04-19 08:53:52,914: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:53:52,965: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:53:54,581: INFO: prediction: Model prediction: [[0.04791145 0.9520886 ]], Shape: (1, 2)]
[2025-04-19 08:53:54,582: ERROR: prediction: Unexpected prediction shape: (1, 2), expected (1, 1)]
[2025-04-19 08:53:54,583: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:53:54] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:54:20,106: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 08:54:20,106: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 08:54:24,627: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:54:24] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:54:42,583: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:54:42,663: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:54:44,464: INFO: prediction: Model prediction: [[0.01242971 0.98757035]], Shape: (1, 2)]
[2025-04-19 08:54:44,467: INFO: prediction: Class: Tumor, Confidence: 0.9875703454017639]
[2025-04-19 08:54:44,468: INFO: prediction: Returning result: {'class': 'Tumor', 'confidence': 0.9875703454017639}]
[2025-04-19 08:54:44,470: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:54:44] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:55:38,991: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:55:38] "GET / HTTP/1.1" 200 -]
[2025-04-19 08:55:49,092: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:55:49,154: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:55:49,571: INFO: prediction: Model prediction: [[0.01242971 0.98757035]], Shape: (1, 2)]
[2025-04-19 08:55:49,571: INFO: prediction: Class: Tumor, Confidence: 0.9875703454017639]
[2025-04-19 08:55:49,572: INFO: prediction: Returning result: {'class': 'Tumor', 'confidence': 0.9875703454017639}]
[2025-04-19 08:55:49,573: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:55:49] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 08:56:30,633: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 08:56:30,673: INFO: prediction: Input image shape: (1, 224, 224, 3)]
[2025-04-19 08:56:31,266: INFO: prediction: Model prediction: [[0.01242971 0.98757035]], Shape: (1, 2)]
[2025-04-19 08:56:31,267: INFO: prediction: Class: Tumor, Confidence: 0.9875703454017639]
[2025-04-19 08:56:31,267: INFO: prediction: Returning result: {'class': 'Tumor', 'confidence': 0.9875703454017639}]
[2025-04-19 08:56:31,268: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 08:56:31] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 09:00:36,142: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:36] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:41,445: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:41] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:44,228: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:44] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:44,908: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:44] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:45,310: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:45] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:45,653: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:45] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:00:46,028: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:00:46] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:04:06,525: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 09:04:06,527: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 09:04:10,648: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:04:10] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:08:26,682: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.166.217:8080]
[2025-04-19 09:08:26,682: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-19 09:08:29,864: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:08:29] "GET / HTTP/1.1" 200 -]
[2025-04-19 09:08:41,597: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 09:08:43,570: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:08:43] "POST /predict HTTP/1.1" 200 -]
[2025-04-19 09:12:18,465: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-19 09:12:20,123: INFO: _internal: 127.0.0.1 - - [19/Apr/2025 09:12:20] "POST /predict HTTP/1.1" 200 -]
